version: "3.9"

x-node-common: &node-common
  image: leslie:latest
  environment:
    RUST_LOG: info
  stop_grace_period: 30s
  init: true

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      leslie:

  node1:
    <<: *node-common
    build: .
    command: ["--id", "node1", "--hostname", "node1", "--port", "50051"]
    environment:
      PROMETHEUS_BIND: 0.0.0.0:9464
    networks:
      leslie:
    ports:
      - "50051:50051"
      - "9141:9464"

  node2:
    <<: *node-common
    command: ["--id", "node2", "--hostname", "node2", "--port", "50052", "--connect", "node1:50051", "--crash-probability", "0.5"]
    environment:
      PROMETHEUS_BIND: 0.0.0.0:9464
    networks:
      leslie:
    ports:
      - "50052:50052"
      - "9142:9464"
    depends_on: [node1]

  node3:
    <<: *node-common
    command: ["--id", "node3", "--hostname", "node3", "--port", "50053", "--connect", "node1:50051"]
    environment:
      PROMETHEUS_BIND: 0.0.0.0:9464
    networks:
      leslie:
    ports:
      - "50053:50053"
      - "9143:9464"
    depends_on: [node1]

  node4:
    <<: *node-common
    command: ["--id", "node4", "--hostname", "node4", "--port", "50054", "--connect", "node1:50051"]
    environment:
      PROMETHEUS_BIND: 0.0.0.0:9464
    networks:
      leslie:
    ports:
      - "50054:50054"
      - "9144:9464"
    depends_on: [node1]

  node5:
    <<: *node-common
    command: ["--id", "node5", "--hostname", "node5", "--port", "50055", "--connect", "node1:50051"]
    environment:
      PROMETHEUS_BIND: 0.0.0.0:9464
    networks:
      leslie:
    ports:
      - "50055:50055"
      - "9145:9464"
    depends_on: [node1]

networks:
  leslie:
    name: leslie
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
